application: wave-email-notifications
version: 1
runtime: python
api_version: 1

handlers:
- url: /_wave/.*
  script: wave-email-notifications.py
- url: /prefs/.*
  script: preferences.py
- url: /send_email/.*
  script: send_email.py
  login: admin
- url: /inc
  static_dir: inc
- url: /
  script: home.py
