application: wave-email-notifications
version: 1
runtime: python
api_version: 1

handlers:
- url: /_wave/.*
  script: notifiy_robot.py
- url: /proc/.*
  script: app.py
- url: /iphone/.*
  script: app.py
- url: /send_email
  script: app.py
  login: admin
- url: /_ah/mail/.+ 
  script: app.py
  login: admin
- url: /
  script: app.py
- url: /
  static_dir: inc

inbound_services:
- mail


