application: wave-email-notifications
version: 1
runtime: python
api_version: 1

handlers:
- url: /_wave/.*
  script: wave-email-notifications.py
- url: /proc
  script: proc.py
- url: /send_email
  script: send_email.py
  login: admin
- url: /
  script: home.py
- url: /
  static_dir: inc
